- CODE_OF_CONDUCT.md
- LICENSE
- SECURITY.md
| Branch?       | 1.x for bc    |
| Bug fix?      | n/a                                                            |
| New feature?  | n/a                   |
| Deprecations? | n/a  |
| Tickets       | Fix #2             |
Add community standards:
- Security policy
- Code of conduct
- License
> [1.x] Add community standards

- docs/contributing/development.md
- docs/contributing/reviewing.md
Fix #6
| Branch?       | 1.x for bc    |
| Bug fix?      | yes                                                            |
| Tickets       | Fix #6 & #7             |
Adds a guide for the local development environment
> [1.x] add development guide

- CONTRIBUTING.md
- docs/contributing/style_guide.md
Fixes #12
| Branch?       | 1.x    |
| Bug fix?      | yes                                                        |
| Tickets       | Fix #12             |
As described per the title.
> [1.x] add style guide

- Dockerfile
| Branch?       | 1.x    |
| Bug fix?      | no                                                          |
| Tickets       | Fix #19             |
install mongodb extension
> install mongodb extension

- .env
- Dockerfile
- docker-compose.yml
- docker/mongo/mongo-init.js
| Branch?       | 1.x    |
| Tickets       | Fix #22             |
> [1.x] prepare docker for local dev

- .php-cs-fixer.dist.php
- composer.json
- composer.lock
- psalm.xml
| Branch?       | 1.x    |
| Deprecations? |no  |
| Tickets       | Fix #17             |
> Config psalm and cs fixer for tests

- .env.test
- .github/workflows/ci.yml
- docs/contributing/development.md
| Tickets       | Fix #30             |
> [1.x] Fix acceptance tests on GH

- config/services.yaml
- src/Foundation/Actions/AbstractAction.php
- src/Foundation/Exceptions/ExceptionListener.php
- src/Foundation/Exceptions/RenderableInterface.php
- src/Foundation/Exceptions/ValidationException.php
| Tickets       | Fix #29             |
Known issues:
- Validation error property path starts with `data` #37
> [1.x] Add global error handler

- composer.json
- composer.lock
- config/bundles.php
- config/packages/framework.yaml
- config/packages/security.yaml
- src/Siklid/Auth/RegisterByEmail.php
- src/Siklid/Document/User.php
- symfony.lock
| Bug fix?      | yes                                                           |
| Tickets       | Fix #32             |
> [1.x] Password hashing

- docker-compose.override.yml
- docker/php/conf.d/app.dev.ini
| Tickets       | Fix #35             |
Starts Xdebug in `develop` and `debug` mode
> [1.x] Fix docker xdebug

- composer.json
- composer.lock
- config/bundles.php
- config/packages/gesdinet_jwt_refresh_token.yaml
- config/packages/security.yaml
- config/routes.yaml
- config/routes/gesdinet_jwt_refresh_token.yaml
- src/Siklid/Document/RefreshToken.php
- src/Siklid/Document/User.php
- symfony.lock
| Bug fix?      | no                                                          |
**Know issues:**
- Unit tests show a deprecation warning #43 
- Routes are not consistent with the login route #44
> [1.x] Generate a refresh token

- tests/Feature/Auth/EmailRegistrationTest.php
| Tickets       | Fix ~#43~             |
> [1.x] Disable the deprecation warning caused by the refresh token package

- .github/workflows/ci.yml
- config/services.yaml
- src/Controller/Auth/RegisterController.php
- src/Siklid/Auth/RegisterByEmail.php
- src/Siklid/Auth/Request/RegisterByEmailRequest.php
- src/Siklid/Auth/Requests/RegisterByEmailRequest.php
- src/Siklid/Auth/Token/AccessTokenInterface.php
- src/Siklid/Auth/Token/HasAccessToken.php
- src/Siklid/Document/AccessToken.php
- src/Siklid/Document/User.php
- src/Siklid/Foundation/Action/AbstractAction.php
- src/Siklid/Foundation/Action/ActionInterface.php
- src/Siklid/Foundation/Action/ValidatableInterface.php
- src/Siklid/Foundation/Constraint/UniqueDocument.php
- src/Siklid/Foundation/Exception/ExceptionListener.php
- src/Siklid/Foundation/Exception/RenderableInterface.php
- src/Siklid/Foundation/Exception/SiklidException.php
- src/Siklid/Foundation/Exception/ValidationException.php
- src/Siklid/Foundation/Http/ApiController.php
- src/Siklid/Foundation/Http/Request.php
- src/Siklid/Foundation/Util/Json.php
- tests/Feature/Auth/EmailRegistrationTest.php
- tests/FeatureTestCase.php
| Bug fix?      | no                                                           |
| Tickets       | Fix #46             |
> [1.x] Add access token to register response

- src/Siklid/Auth/RegisterByEmail.php
- src/Siklid/Auth/Token/AccessTokenInterface.php
- src/Siklid/Auth/Token/TokenManager.php
- src/Siklid/Auth/Token/TokenManagerInterface.php
- src/Siklid/Document/AccessToken.php
- src/Siklid/Document/User.php
- tests/Feature/Auth/EmailRegistrationTest.php
| Tickets       | Fix #48             |
> [1.x] Add refresh token to access token response

- config/services.yaml
- src/Controller/Auth/RegisterController.php
- src/Foundation/Action/AbstractAction.php
- src/Foundation/Action/ActionInterface.php
- src/Foundation/Action/ValidatableInterface.php
- src/Foundation/Constraint/UniqueDocument.php
- src/Foundation/Exception/ExceptionListener.php
- src/Foundation/Exception/RenderableInterface.php
- src/Foundation/Exception/SiklidException.php
- src/Foundation/Exception/ValidationException.php
- src/Foundation/Http/ApiController.php
- src/Foundation/Http/Request.php
- src/Foundation/Util/Json.php
- src/Siklid/Application/Auth/Forms/UserType.php
- src/Siklid/Application/Auth/RegisterByEmail.php
- src/Siklid/Application/Auth/Request/RegisterByEmailRequest.php
- src/Siklid/Application/Auth/Token/AccessTokenInterface.php
- src/Siklid/Application/Auth/Token/HasAccessToken.php
- src/Siklid/Application/Auth/Token/TokenManager.php
- src/Siklid/Application/Auth/Token/TokenManagerInterface.php
- src/Siklid/Document/AccessToken.php
- src/Siklid/Document/User.php
- tests/FeatureTestCase.php
- tests/IntegrationTestCase.php
> [1.x] Code cleanup

- CONTRIBUTING.md
- docs/contributing/reporting.md
| Tickets       | Fix #8            |
> [1.x] Add reporting doc

- tests/DBTrait.php
- tests/Feature/Auth/EmailRegistrationTest.php
- tests/FeatureTestCase.php
- tests/Integration/Siklid/Command/SetupCommandTest.php
- tests/IntegrationTestCase.php
| Tickets       | Fix #57             |
**Removes**
- the `dropAllCollections` method on tests teardown
**Adds**
- the `deleteDocument` method
> [1.x] Fix tests `teardown` method

- tests/DBTrait.php
| Bug fix?      | no                                                          |
| New feature?  | yes                  |
> [1.x] delete document can accept a document object

- composer.json
- composer.lock
- config/packages/doctrine_mongodb.yaml
- src/Foundation/Util/Assert.php
- src/Foundation/ValueObject/Email.php
- src/Foundation/ValueObject/EmailType.php
- src/Siklid/Document/User.php
- tests/TestCase.php
- tests/Unit/Foundation/Exception/ValidationExceptionTest.php
- tests/Unit/Foundation/Util/AssertionTest.php
- tests/Unit/Foundation/ValueObject/EmailTest.php
| Tickets       | Fix #60             |
> [1.x] Implement email value object

- composer.json
- composer.lock
- config/packages/doctrine_mongodb.yaml
- src/Foundation/ValueObject/Email.php
- src/Foundation/ValueObject/Slug.php
- src/Foundation/ValueObject/SlugType.php
- src/Siklid/Document/User.php
- tests/Feature/Auth/EmailRegistrationTest.php
- tests/Unit/Foundation/ValueObject/EmailTest.php
- tests/Unit/Foundation/ValueObject/SlugTest.php
| Bug fix?      | no                                                           |
| Tickets       | Fix #62             |
This PR opens: #63
> Add slug type

- .gitignore
- docs/contributing/development.md
- src/Foundation/Constraint/IsSlug.php
- src/Foundation/Validator/IsSlugValidator.php
- src/Foundation/ValueObject/Slug.php
- src/Siklid/Document/User.php
- tests/Unit/Foundation/ValueObject/SlugTest.php
- tests/Unit/Siklid/Document/UserTest.php
| Tickets       | Fix #63             |
This PR opens #66
> [1.x] Add slug constraint

- config/packages/doctrine_mongodb.yaml
- src/Foundation/Constraint/Slug.php
- src/Foundation/Constraint/Username.php
- src/Foundation/Validator/SlugValidator.php
- src/Foundation/Validator/UsernameValidator.php
- src/Foundation/ValueObject/EmailType.php
- src/Foundation/ValueObject/SlugType.php
- src/Foundation/ValueObject/Username.php
- src/Foundation/ValueObject/UsernameType.php
- src/Siklid/Document/User.php
- tests/Feature/Auth/EmailRegistrationTest.php
- tests/Unit/Foundation/ValueObject/UsernameTest.php
| Tickets       | Fix #66             |
> [1.x] Add username type and value object

- src/Foundation/Validator/UsernameValidator.php
- src/Siklid/Document/User.php
| Bug fix?      | yes                                                         |
| Tickets       | Fix #70            |
> [1.x] Fix username validator

- composer.json
- docker-compose.override.yml
- docker/php/conf.d/app.dev.ini
- docs/contributing/development.md
| Deprecations? | no |
| Tickets       | Fix #69             |
- Fix #69
- Add PHPStorm doc notes
> [1.x]: allow develop, debug and coverage modes

- config/packages/security.yaml
- config/routes.yaml
- config/routes/gesdinet_jwt_refresh_token.yaml
- src/Foundation/Exception/ExceptionListener.php
- src/Foundation/Http/ApiController.php
- src/Siklid/Application/Auth/LoginFailureHandler.php
- src/Siklid/Application/Auth/LoginSuccessHandler.php
- tests/DBTrait.php
- tests/Feature/Auth/EmailAuthTest.php
- tests/FeatureTestCase.php
- tests/Unit/Foundation/Http/ApiControllerTest.php
- tests/Unit/Siklid/Application/Auth/LoginSuccessHandlerTest.php
| Tickets       | Fix #53             |
> [1.x] add endpoint for email login

- config/packages/security.yaml
- config/routes.yaml
| Tickets       | Fix #44             |
> [1.x] update refresh token route config

- .github/dependabot.yml
> [1.x] add dependabot

- CONTRIBUTING.md
- docs/README.md
- docs/contributing/development.md
> [1.x] Update contribution guide

- src/Foundation/Util/Json.php
- tests/Unit/Foundation/Util/JsonTest.php
| Tickets       | Fix #73             |
> add array To Json

- composer.json
- composer.lock
- src/Foundation/Exception/ValidationException.php
- src/Foundation/ValueObject/Email.php
- src/Siklid/Form/UserType.php
- tests/Unit/Foundation/ValueObject/EmailTest.php
| Bug fix?      | yes                                                            |
Validation on the public static factory `Email::fromString()` causes a malformed validation error message on JSON responses.
> [1.x] Fix email type

- .github/ISSUE_TEMPLATE/1_Bug_report.yaml
- .github/ISSUE_TEMPLATE/2_Feature_request.yaml
- .github/dependabot.yml
> [1.x] Fix issue templates

- config/packages/lexik_jwt_authentication.yaml
| Bug fix?      | yes                                                           |
| New feature?  | no                  |
| Tickets       | Fix #107             |
> [1.x] fix user identity field

- composer.json
- composer.lock
- config/bundles.php
- config/packages/sensio_framework_extra.yaml
- config/services.yaml
- symfony.lock
| Tickets       | Fix #110             |
> [1.x] param converter for the odm

- src/Foundation/ValueType/CoercibleEnum.php
- src/Foundation/ValueType/SpecificType.php
- src/Siklid/Application/Contract/Type/RepetitionAlgorithm.php
| Bug fix?      | yes                                                           |
| Tickets       | Fix #111            |
> [1.x] Add CoercibleEnum interface

- composer.json
- composer.lock
- config/packages/sensio_framework_extra.yaml
- src/Controller/BoxController.php
- src/Foundation/Exception/ExceptionListener.php
- src/Foundation/Exception/LogicException.php
- src/Siklid/Application/Box/DeleteBox.php
- src/Siklid/Application/Contract/Entity/BoxInterface.php
- src/Siklid/Document/Box.php
- src/Siklid/Security/Voter/BoxVoter.php
- tests/Concerns/BoxFactoryTrait.php
- tests/Concerns/FactoryConcern.php
- tests/Concerns/UserFactoryTrait.php
- tests/Feature/Box/DeleteBoxTest.php
- tests/FeatureTestCase.php
- tests/Unit/Foundation/Exception/ExceptionListenerTest.php
- tests/Unit/Siklid/Document/BoxTest.php
- tests/Unit/Siklid/Security/Voter/BoxVoterTest.php
| Tickets       | Fix #97             |
**TODO**
> [1.x] user can delete her box

- docker-compose.yml
This PR adds a Redis container to the docker-compose.
> [1.x] Add Redis container

- composer.json
- composer.lock
> chore(deps): set platform

- tests/Concern/Assertion/AssertODMTrait.php
- tests/Concern/Assertion/AssertResponseTrait.php
- tests/Concern/Assertion/ResponseAssertion.php
- tests/Concern/KernelTestCaseTrait.php
- tests/Concern/WebTestCaseTrait.php
This PR segregates assertion traits for better extensibility.
> [1.x] Segregate traits

- tests/Feature/Auth/EmailAuthTest.php
- tests/Feature/Box/CreateBoxTest.php
> [1.x] assert response content

- src/Foundation/Validation/Constraint/Slug.php
- src/Foundation/Validation/Constraint/SlugValidator.php
- src/Foundation/Validation/Constraint/UniqueDocument.php
- src/Foundation/Validation/Constraint/Username.php
- src/Foundation/Validation/Constraint/UsernameValidator.php
- src/Siklid/Document/User.php
- tests/Foundation/Validation/Constraint/SlugTest.php
- tests/Foundation/Validation/Constraint/SlugValidatorTest.php
- tests/Foundation/Validation/Constraint/UniqueDocumentTest.php
- tests/Foundation/Validation/Constraint/UsernameTest.php
- tests/Foundation/Validation/Constraint/UsernameValidatorTest.php
This PR groups all classes related to validation into a single namespace
> [1.x] Group all validation related classes in a single namespace

- tests/Concern/Assertion/AssertResponseTrait.php
- tests/Concern/WebTestCaseTrait.php
- tests/Feature/Auth/EmailAuthTest.php
- tests/Feature/Box/CreateBoxTest.php
- tests/Feature/Box/ListBoxTest.php
> [1.x] code refactoring client tests

- src/Foundation/Action/AbstractAction.php
- src/Siklid/Application/Box/CreateBox.php
- src/Siklid/Application/Flashcard/CreateFlashcard.php
- src/Siklid/Repository/BoxRepository.php
- src/Siklid/Security/UserResolver.php
- src/Siklid/Security/UserResolverInterface.php
- tests/Siklid/Security/UserResolverTest.php
| Bug fix?      | yes                                                           |
| Tickets       | Fix #165             |
> [1.x] Decouple action from controller

- src/Foundation/Security/Token/TokenSubscriber.php
- tests/Foundation/Security/Token/TokenSubscriberTest.php
| Bug fix?      | no                                                           |
| Tickets       | #54             |
This PR is one of the steps for #54: It verifies if the token is revoked or not.
> [1.x] Add token subscriber

- .github/workflows/ci.yml
- composer.lock
- tests/Foundation/Validation/Constraint/ExistsValidatorTest.php
- tests/Siklid/Document/BoxTest.php
| Bug fix?      | yes                                                            |
| New feature?  | no                 |
| Deprecation? | no |
| Tickets       | #228             |
This PR only fixes PHPunit deprecation warnings. Upgrade to PHPUNIT 10 still not possible because of other dependencies. 
**TODO**
> [1.x] Fix PHPUNIT warnings

- docs/contributing/development.md
| Bug fix?      | yes                                                         |
| Tickets       |  N/A            |
> [1.x] fix instruction to stop containers

- .github/ISSUE_TEMPLATE/3_Task.Yaml
| Bug fix?      | N/A                                                          |
| New feature?  | N/A                   |
| Deprecations? | N/A  |
| Tickets       | Fix #258            |
As per the title
> [1.x] Add task template

- docs/README.md
- docs/technical/README.md
- docs/technical/security/authentication.md
- docs/technical/security/authorization.md
- src/Foundation/Security/Authorization/AbstractVoter.php
- src/Siklid/Application/Contract/Entity/FlashcardInterface.php
- src/Siklid/Application/Flashcard/CreateFlashcard.php
- src/Siklid/Application/Flashcard/FlashcardVoter.php
- src/Siklid/Document/Flashcard.php
- tests/Foundation/Security/Authorization/AbstractVoterTest.php
- tests/Siklid/Application/Flashcard/FlashcardVoterTest.php
| Tickets       | Fix #260             |
**This PR adds:**
- Abstract voter class to be extended by all voters
- A documentation for voters
- A voter for flashcards
> [1.x] create a card voter

- src/Foundation/Security/Authorization/AbstractVoter.php
- src/Siklid/Application/Box/BoxVoter.php
- tests/Siklid/Application/Box/BoxVoterTest.php
| Tickets       | Fix #268             |
| Description | Updates the box voter to extend the abstract voter |
> [Box] Update the box voter

- composer.json
- composer.lock
- psalm.xml
- src/Siklid/Repository/BoxRepository.php
| Bug fix?      | n/a                                                            |
| New feature?  | n/a                  |
| Deprecations? | n/a  |
| Tickets       | Fix #281             |
> [deps]: bump psalm to v5

- composer.json
- composer.lock
- config/bundles.php
- config/packages/sensio_framework_extra.yaml
- config/services.yaml
- src/Controller/BoxController.php
- src/Siklid/Application/Box/DeleteBox.php
- src/Siklid/Document/Box.php
- symfony.lock
This reverts commit aafdfd42d7f0c5d383692d0d0dc06c040b799c6d.
| Bug fix?      | n/a                                                          |
| New feature?  | n/a                   |
| Deprecations? | n/a  |
| Tickets       | Fix #280             |
> [deps] remove sensio/framework-extra-bundle

- .github/dependabot.yaml
This PR improves the dependabot configurations
> [Deps] Maintain dependabot config

- .env
- composer.json
- composer.lock
- config/packages/mailer.yaml
- docker-compose.override.yml
- symfony.lock
| Bug fix?      | n/a                                                             |
| New feature?  | n/a                   |
| Deprecations? | n/a |
| Tickets       | Fix #289             |
This is an alternative to #288 
You can find more information in Symfony docs: 
https://symfony.com/doc/current/mailer.html#development-debugging
> [Mail]: install symfony mailer

- .github/workflows/ci.yml
- .php-cs-fixer.dist.php
- Dockerfile
- composer.json
- composer.lock
- Closes #257
| Bug fix?      | n/a                                                            |
| New feature?  | n/a                   |
| Deprecations? | n/a  |
| Tickets       | Fix #257             |
> [deps]: upgrade to php8.2

- .github/PULL_REQUEST_TEMPLATE.md
- composer.json
- composer.lock
- config/bundles.php
- phpunit.xml.dist
- src/Foundation/Action/Config.php
- src/Foundation/Exception/ExceptionListener.php
- src/Foundation/Exception/ValidationException.php
- src/Foundation/Security/Authorization/AbstractVoter.php
- src/Siklid/Application/Auth/RegisterByEmail.php
- src/Siklid/Application/Auth/Request/LogoutRequest.php
- src/Siklid/Application/Auth/Request/RegisterRequest.php
- src/Siklid/Application/Box/CreateBox.php
- src/Siklid/Application/Box/Request/CreateBoxRequest.php
- src/Siklid/Application/Flashcard/Request/CreateFlashcardRequest.php
- symfony.lock
- tests/Concern/Assertion/AssertResponseTrait.php
- tests/Concern/Util/JsonRequestTrait.php
- tests/Concern/WebTestCaseTrait.php
- tests/Feature/Auth/EmailAuthFeature.php
- tests/Feature/Auth/LogoutFeature.php
- tests/Feature/Box/CreateBoxFeature.php
- tests/Feature/Box/DeleteBoxFeature.php
- tests/Feature/Box/ListBoxFeature.php
- tests/Feature/Flashcard/CreateFlashcardFeature.php
- tests/Feature/Flashcard/DeleteFlashCardFeature.php
- tests/Feature/Flashcard/ViewFlashcardFeature.php
- tests/Foundation/Exception/ValidationExceptionTest.php
- tests/Siklid/Application/Auth/Request/LogoutRequestTest.php
| Tickets       | N/A            |
> [http] Use the symblaze http bundle
